/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entities.Record;
import Utilities.RecordManager;

/**
 *
 * @author Westy
 */
public class frmMainForm extends javax.swing.JFrame {

    /**
     * Creates new form fmMainForm
     */
        
    public frmMainForm() {
        this.setLocation(225, 40);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        spnAge = new javax.swing.JSpinner();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboxQ1yes = new javax.swing.JCheckBox();
        cboxQ1No = new javax.swing.JCheckBox();
        cboxQ2yes = new javax.swing.JCheckBox();
        cboxQ2No = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblContactError = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        lblEmailAddressError = new javax.swing.JLabel();
        lblTempError = new javax.swing.JLabel();
        spnTemp = new javax.swing.JSpinner();
        lblSurnameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Covid-19 Contact Tracer  Register");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(253, 245, 225));
        jPanel1.setForeground(new java.awt.Color(253, 245, 225));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 124, 81));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 124, 81));
        jLabel2.setText("Surname");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 124, 81));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Covid-10 Contact Tracer Register");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 124, 81));
        jLabel4.setText("Contact");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 124, 81));
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 124, 81));
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 124, 81));
        jLabel7.setText("Email Address");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 124, 81));
        jLabel8.setText("Temperature");

        jLabel10.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 124, 81));
        jLabel10.setText("Please complete the form");

        txtName.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtSurname.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtSurname.setBorder(null);
        txtSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSurnameFocusLost(evt);
            }
        });

        txtContact.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtContact.setBorder(null);
        txtContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactFocusLost(evt);
            }
        });

        spnAge.setModel(new javax.swing.SpinnerNumberModel(16, 0, 100, 1));
        spnAge.setBorder(null);

        txtAddress.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtAddress.setBorder(null);
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 124, 81));
        jLabel9.setText("Have u had any covid-19 symptoms: Fever (over 38 degrees), dry cough or shortness of breath?");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 124, 81));
        jLabel11.setText("Have you been exposed to anyone with COVID-19 or someone who has sysmptoms in the last 4 weeks?");

        cboxQ1yes.setBackground(new java.awt.Color(253, 245, 225));
        cboxQ1yes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboxQ1yes.setForeground(new java.awt.Color(255, 124, 81));
        cboxQ1yes.setText("Yes");
        cboxQ1yes.setBorder(null);
        cboxQ1yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxQ1yesActionPerformed(evt);
            }
        });

        cboxQ1No.setBackground(new java.awt.Color(253, 245, 225));
        cboxQ1No.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboxQ1No.setForeground(new java.awt.Color(255, 124, 81));
        cboxQ1No.setText("No");
        cboxQ1No.setBorder(null);
        cboxQ1No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxQ1NoActionPerformed(evt);
            }
        });

        cboxQ2yes.setBackground(new java.awt.Color(253, 245, 225));
        cboxQ2yes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboxQ2yes.setForeground(new java.awt.Color(255, 124, 81));
        cboxQ2yes.setText("Yes");
        cboxQ2yes.setBorder(null);
        cboxQ2yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxQ2yesActionPerformed(evt);
            }
        });

        cboxQ2No.setBackground(new java.awt.Color(253, 245, 225));
        cboxQ2No.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboxQ2No.setForeground(new java.awt.Color(255, 124, 81));
        cboxQ2No.setText("No");
        cboxQ2No.setBorder(null);
        cboxQ2No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxQ2NoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 79, 21));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(253, 245, 225));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 79, 21));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(253, 245, 225));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 79, 21));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(253, 245, 225));
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblNameError.setForeground(new java.awt.Color(204, 51, 0));
        lblNameError.setText("  ");

        lblContactError.setForeground(new java.awt.Color(204, 51, 0));
        lblContactError.setText("  ");

        lblAddressError.setForeground(new java.awt.Color(204, 51, 0));
        lblAddressError.setText("  ");

        lblEmailAddressError.setForeground(new java.awt.Color(204, 51, 0));
        lblEmailAddressError.setText("  ");

        lblTempError.setForeground(new java.awt.Color(204, 51, 0));
        lblTempError.setText("  ");

        spnTemp.setModel(new javax.swing.SpinnerNumberModel(16, 0, 100, 1));
        spnTemp.setBorder(null);

        lblSurnameError.setForeground(new java.awt.Color(204, 51, 0));
        lblSurnameError.setText("     ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboxQ1No)
                    .addComponent(cboxQ1yes))
                .addContainerGap(717, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblContactError, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(spnTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTempError, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtName)
                                            .addComponent(txtSurname)
                                            .addComponent(txtAddress)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSurnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblEmailAddressError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                                .addComponent(lblAddressError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 106, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxQ2yes)
                            .addComponent(cboxQ2No)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(487, 487, 487)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurnameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAddressError))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTempError)
                    .addComponent(spnTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxQ1yes)
                .addGap(18, 18, 18)
                .addComponent(cboxQ1No)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxQ2yes)
                .addGap(18, 18, 18)
                .addComponent(cboxQ2No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //record form.
        Record Record = null;
        if(formIsValid()){
            Record = new Record(txtName.getText(),txtSurname.getText(),txtContact.getText(),(int)spnAge.getValue(),
            txtAddress.getText(),txtEmail.getText(),(int)spnTemp.getValue(),getSelectedQ1(),getSelectedQ2()); 
            new Frames.frmMainMessage(this,RecordManager.storeRecord(Record)).show();
            //clear form
            clear();
        }else{
            new Frames.frmMainMessage(this,"Form not complete!").show();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clear(){
        txtName.setText("");
        txtSurname.setText("");
        txtContact.setText("");
        spnAge.setValue(0);
        txtAddress.setText("");
        txtEmail.setText("");
        spnTemp.setValue(0);
        cboxQ1No.setSelected(false);
        cboxQ1yes.setSelected(false);
        cboxQ2No.setSelected(false);
        cboxQ2yes.setSelected(false);
    }
    
    public boolean formIsValid(){
        if(!valName()){
            return false;
        }else if(!valSurname()){
            return false;
        }else if(!valCont()){
            return false;
        }else if(!valAddress()){
            return false;
        }else if(!valEmail()){
            return false;
        }else{
            return true;
        }
    }
    
    private boolean valName(){
        if(txtName.getText().isEmpty()){
            lblNameError.setText("empty field!");
            return false;
        }else{
            lblNameError.setText("");
            return true;
        }
    }
    private boolean valSurname(){
        if(txtSurname.getText().isEmpty()){
            lblSurnameError.setText("empty field!");
            return false;
        }else{
            lblSurnameError.setText("");
            return true;
        }
    }
    private boolean valCont(){

        if(txtContact.getText().isEmpty()){
            lblContactError.setText("empty field!");
            return false;
        }else if(txtContact.getText().length() != 10){
            lblContactError.setText("10-digit number only!");
            return false;
        }
        lblContactError.setText("");
        return true;
    }
    private boolean valAddress(){
        if(txtAddress.getText().isEmpty()){
            lblAddressError.setText("empty field!");
            return false;
        }else{
            lblAddressError.setText("");
            return true;
        }
    }
    private boolean valEmail(){
        if(txtEmail.getText().isEmpty()){
            lblEmailAddressError.setText("empty field!");
            return false;
        }else{
            lblEmailAddressError.setText("");
            return true;
        }
    }
    
    private int getSelectedQ1(){
        if(cboxQ1yes.isSelected()){
            return 1;
        }else{
            return 0;
        }
    }
    
    private int getSelectedQ2(){
        if(cboxQ2yes.isSelected()){
            return 1;
        }else{
            return 0;
        }
    }
    
    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        valName();
    }//GEN-LAST:event_txtNameFocusLost

    private void txtSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSurnameFocusLost
        // TODO add your handling code here:
        valSurname();
    }//GEN-LAST:event_txtSurnameFocusLost

    private void txtContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactFocusLost
        // TODO add your handling code here:
        valCont();
    }//GEN-LAST:event_txtContactFocusLost

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        // TODO add your handling code here:
        valAddress();
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        valEmail();
    }//GEN-LAST:event_txtEmailFocusLost

    private void cboxQ1yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxQ1yesActionPerformed
        // TODO add your handling code here:
        if(cboxQ1yes.isSelected()){
            cboxQ1No.setSelected(false);
        }
    }//GEN-LAST:event_cboxQ1yesActionPerformed

    private void cboxQ1NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxQ1NoActionPerformed
        // TODO add your handling code here:
        if(cboxQ1No.isSelected()){
            cboxQ1yes.setSelected(false);
        }
    }//GEN-LAST:event_cboxQ1NoActionPerformed

    private void cboxQ2yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxQ2yesActionPerformed
        // TODO add your handling code here:
        if(cboxQ2yes.isSelected()){
            cboxQ2No.setSelected(false);
        }
    }//GEN-LAST:event_cboxQ2yesActionPerformed

    private void cboxQ2NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxQ2NoActionPerformed
        // TODO add your handling code here:
        if(cboxQ2No.isSelected()){
            cboxQ2yes.setSelected(false);
        }
    }//GEN-LAST:event_cboxQ2NoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cboxQ1No;
    private javax.swing.JCheckBox cboxQ1yes;
    private javax.swing.JCheckBox cboxQ2No;
    private javax.swing.JCheckBox cboxQ2yes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblContactError;
    private javax.swing.JLabel lblEmailAddressError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblSurnameError;
    private javax.swing.JLabel lblTempError;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JSpinner spnTemp;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
